<a href="https://colab.research.google.com/github/tajuar-akash-hub/NLP/blob/main/Email_Classification_using_Bert_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Version needed for this project

In [20]:
!pip install tensorflow==2.15.0 keras==2.15 tensorflow-hub==0.13.0 tensorflow-text==2.15.0



   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 68.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.6/100.6 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 33.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 23.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 70.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 32.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 7.3 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.0
    Uninstalling wrapt-1.17.0:
      Successfully uninstalled wrapt-1.17.0
  Attempting uninstall: tensorflow-hub
    Found existing installation: tensorflow-hub 0.16.1
    Uninstalling tensorflow-hub-0.16.1:
      Successfully uninstalled tensorflow-hub-0.16.1
  Attempting uninstall: ml-dtypes
 

In [21]:
import keras
from keras.layers import Input


In [22]:
import tensorflow_hub as hub
import tensorflow_text as text
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [ ]:
# !pip install --upgrade tensorflow tensorflow-hub


# Bi-directinal encoder representation from Transformer

In [ ]:
import tensorflow_hub as hub
import tensorflow_text as text
import tensorflow as tf

# Basic About Bert

In [ ]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"    #L = layer , H= hidden state , A = attention

#here we are using basic bert encoder

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [ ]:
text_test = ['nice movie indeed','I love python programming']

text_preprocessed = bert_preprocess_model(text_test)

text_preprocessed.keys()  #to see all the keys of that dictionary


dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

# Let's see what's invidual elements does in that dictionary

In [ ]:
text_preprocessed['input_mask']

#how this works

#CLS nice movie indeed SEP (sep for separator)   total tokens 5   , maximum length of the sentence = 128

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
text_preprocessed['input_type_ids']  #for our case it's not that usefull

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
text_preprocessed['input_word_ids']
#id for CLS = 101 and for SEP = 102

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

##  Bert Model

In [ ]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [ ]:
bert_results['pooled_output']  #embedding for entire sentence

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177403, -0.21411912,  0.49769545, ...,  0.24465235,
        -0.47334474,  0.81758696],
       [-0.91712314, -0.47935176, -0.7865697 , ..., -0.6175175 ,
        -0.71026856,  0.921843  ]], dtype=float32)>

In [ ]:
bert_results['sequence_output']  #embedding for each token in that sentence

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292047,  0.08567817,  0.14476831, ..., -0.09677088,
          0.08722127,  0.07711085],
        [ 0.1783942 , -0.19006078,  0.5034952 , ..., -0.05869824,
          0.32717073, -0.15578493],
        [ 0.18701449, -0.43388748, -0.4887515 , ..., -0.15502778,
          0.00145182, -0.24471016],
        ...,
        [ 0.12083091,  0.12884252,  0.46453542, ...,  0.0737552 ,
          0.17441946,  0.16522075],
        [ 0.07967882, -0.01190652,  0.502254  , ...,  0.13777725,
          0.21002197,  0.00624588],
        [-0.07212701, -0.28303462,  0.59033376, ...,  0.475519  ,
          0.16668482, -0.08920349]],

       [[-0.0790059 ,  0.36335096, -0.21101595, ..., -0.17183761,
          0.16299714,  0.6724268 ],
        [ 0.27883548,  0.43716297, -0.35764822, ..., -0.04463654,
          0.38315183,  0.5887981 ],
        [ 1.2037671 ,  1.0727016 ,  0.48408663, ...,  0.24921048,
          0.407309  ,  0.40481755],
        ...,

In [ ]:
bert_results['encoder_outputs']  #embedding for each layer

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.1290144 ,  0.00644745, -0.03614967, ...,  0.04999624,
           0.06149195, -0.02657542],
         [ 1.1753386 ,  1.2140785 ,  1.1569982 , ...,  0.11634357,
          -0.3585537 , -0.40490186],
         [ 0.03859041,  0.5386997 , -0.2108978 , ...,  0.21858197,
           0.7260168 , -1.1158606 ],
         ...,
         [-0.07587015, -0.25421894,  0.7075512 , ...,  0.50541997,
          -0.1887868 ,  0.15028352],
         [-0.16066599, -0.28089687,  0.5759707 , ...,  0.5275855 ,
          -0.11141382,  0.02887543],
         [-0.04428157, -0.20279568,  0.59093547, ...,  0.8133835 ,
          -0.39075816, -0.02601742]],
 
        [[ 0.18903585,  0.02752551, -0.06513745, ..., -0.00620203,
           0.15053892,  0.0316545 ],
         [ 0.5916147 ,  0.7589138 , -0.07240658, ...,  0.61903954,
           0.8292891 ,  0.16161972],
         [ 1.4460826 ,  0.44602674,  0.40990272, ...,  0.48255897,
           0.6269117 ,  0.13

In [ ]:
len(bert_results['encoder_outputs'])

12

# **Email classfication  , spam/not spam**
### purpose of Bert is to generate embedding vector for entire sentence

In [1]:
!git clone "https://github.com/tajuar-akash-hub/Datasets"

Cloning into 'Datasets'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 26 (delta 6), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (26/26), 2.51 MiB | 2.09 MiB/s, done.
Resolving deltas: 100% (6/6), done.


In [2]:
import numpy as np
import pandas as pd



In [3]:
df = pd.read_csv("/content/Datasets/spam.csv", encoding='latin1')


In [4]:
df = pd.read_csv("/content/Datasets/spam.csv", encoding='latin1').drop(columns=["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])


In [5]:
df.head()

category                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.groupby('category').describe()

message                                                            \
           count unique                                                top   
category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    653  Please call our customer service representativ...   

               
         freq  
category       
ham        30  
spam        4

## Handling Imbalance issue (downsampling)

In [ ]:
df.category.value_counts()

category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
#percentile distribution

747/4825

0.15481865284974095

In [6]:
df_spam = df[ df['category'] =='spam' ]
df_ham = df[ df['category'] =='ham' ]


In [7]:
df_spam.shape

(747, 2)

In [ ]:
df_ham.shape

(4825, 5)

In [8]:
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(747, 2)

In [14]:
df_balanced = pd.concat([df_ham_downsampled, df_spam])

df_balanced.shape

(1494, 2)

In [13]:
df_balanced.value_counts('category')

category
ham     747
spam    747
Name: count, dtype: int64

In [12]:
df_balanced.sample(5)

category                                            message
1859      ham          What's up. Do you want me to come online?
1447      ham  Don‰Û÷t give a flying monkeys wot they think a...
2037      ham                           Oh sorry please its over
2773     spam  How come it takes so little time for a child w...
787      spam  Ever thought about living a good life with a p...

In [23]:
#droping unnecessary column

df_balanced.drop('Unnamed: 2',axis='columns',inplace=True)
df_balanced.drop('Unnamed: 3',axis='columns',inplace=True)
df_balanced.drop('Unnamed: 4',axis='columns',inplace=True)

KeyError: "['Unnamed: 2'] not found in axis"

In [16]:
df_balanced.sample(5)

category                                            message
1128     spam  Ur HMV Quiz cash-balance is currently å£500 - ...
3904     spam  Do you want a new video handset? 750 anytime a...
2900     spam  Ur cash-balance is currently 500 pounds - to m...
1622     spam  U have a secret admirer who is looking 2 make ...
3618     spam  8007 25p 4 Alfie Moon's Children in Need song ...

In [17]:
df_balanced['spam']=df_balanced['category'].apply(lambda x: 1 if x=='spam' else 0)
df_balanced.sample(5)

category                                            message  spam
2624      ham                        S da..al r above  &lt;#&gt;     0
1662     spam  Hi if ur lookin 4 saucy daytime fun wiv busty ...     1
4966     spam  You can donate å£2.50 to UNICEF's Asian Tsunam...     1
2853      ham  Haha... Hope Ì_ can hear the receipt sound... ...     0
4766     spam  Your unique user ID is 1172. For removal send ...     1

## Train test split

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_balanced['message'],df_balanced['spam'], stratify=df_balanced['spam'])



### '''
The stratify parameter in the train_test_split function ensures that the proportion of the classes in the target variable (y) remains the
same in both the training and testing sets as it is in the original dataset.
This is particularly important when dealing with imbalanced datasets where one class significantly outnumbers the other.

so no train and test size, it will pick automatically
'''

In [ ]:
X_train.shape

(1120,)

In [ ]:
y_train.shape

(1120,)

In [ ]:
X_test.shape

(374,)

In [ ]:
X_train.head(5)

818                           Then why you not responding
2765             and  picking them up from various points
1826    Dude. What's up. How Teresa. Hope you have bee...
865     Congratulations ur awarded either a yrs supply...
4766    Your unique user ID is 1172. For removal send ...
Name: message, dtype: object

## **Implement Bert**

In [24]:
    #L = layer , H= hidden state , A = attention

bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [25]:
#function

def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)  #it return a dictionary
    return bert_encoder(preprocessed_text)['pooled_output']  #from dictionary we're only taking 'pooled output'


#what is pooled output ?

get_sentence_embeding([
    "500$ discount. hurry up",
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.843517  , -0.5132727 , -0.8884572 , ..., -0.7474886 ,
        -0.75314724,  0.91964495],
       [-0.8720834 , -0.50543964, -0.94446665, ..., -0.8584749 ,
        -0.7174534 ,  0.88082975]], dtype=float32)>

In [26]:
e = get_sentence_embeding([
    "Mahir",
    "Tajuar",
    "Akash",
    "sky"

])

print(e)

tf.Tensor(
[[-0.7230879  -0.27770248  0.33876425 ...  0.31644672 -0.5949765
   0.70040405]
 [-0.79849416 -0.1939021   0.22567564 ...  0.27979967 -0.555724
   0.7727929 ]
 [-0.81268835 -0.28569722 -0.23106247 ...  0.06453508 -0.5763292
   0.7855321 ]
 [-0.85641044 -0.27149698  0.3252376  ...  0.40447882 -0.63309085
   0.87864876]], shape=(4, 768), dtype=float32)


## what is pooled output?

The `pooled_output` in a BERT model refers to a representation of the entire input sequence as a single vector, which is often used for tasks like classification. Here's a detailed explanation:

---

### **What is `pooled_output`?**
- BERT processes input sequences through multiple transformer layers and generates contextual embeddings for each token in the sequence.
- The final hidden states for all tokens are output as a matrix (sequence of vectors). This is often referred to as the **token embeddings**.
- The `[CLS]` token (a special classification token added at the beginning of the sequence) is designed to represent the entire sequence.
- The **pooled output** is essentially the embedding of this `[CLS]` token after it has been further processed by a dense layer (pooling layer) with a tanh activation function.

---

### **Key Points About `pooled_output`:**
1. **Represents the Entire Sequence:**
   - While the token embeddings capture contextual information for individual tokens, `pooled_output` is a fixed-size vector summarizing the entire input sequence.

2. **Size of `pooled_output`:**
   - It is always of size `hidden_size` (e.g., 768 for BERT-Base and 1024 for BERT-Large), regardless of the input sequence length.

3. **Primary Use:**
   - Used for tasks that require a single representation of the input, such as:
     - Text classification (e.g., spam detection, sentiment analysis).
     - Sentence similarity (e.g., determining how similar two sentences are).
   - It serves as the input for the classification head in fine-tuning tasks.

4. **Derived from `[CLS]`:**
   - BERT outputs token embeddings for all tokens and uses the `[CLS]` token's representation as the pooled embedding.
   - A pooling layer (often a dense layer) refines the `[CLS]` embedding to create the `pooled_output`.

---

### **Difference Between `pooled_output` and Token Embeddings:**
| Aspect             | `pooled_output`                     | Token Embeddings                  |
|--------------------|-------------------------------------|------------------------------------|
| **Purpose**         | Represents the entire sequence.     | Represents individual tokens.      |
| **Size**            | Fixed size (`hidden_size`, e.g., 768).| Varies based on the sequence length. |
| **Usage**           | Text-level tasks (e.g., classification). | Token-level tasks (e.g., NER, QA). |
| **Source**          | Comes from `[CLS]` token embedding. | Comes from all token embeddings.   |

---

### **Example Use in Code:**
```python
def get_sentence_embedding(sentences):
    # Preprocess text using BERT tokenizer and preprocessing model
    preprocessed_text = bert_preprocess_model(sentences)
    
    # Pass preprocessed text through BERT model
    outputs = bert_model(preprocessed_text)
    
    # Extract pooled_output
    pooled_output = outputs['pooled_output']
    
    return pooled_output
```

Here, `pooled_output` is a fixed-size embedding vector summarizing the content of the `sentences`.

---

### **Why Use `pooled_output`?**
- When you need a concise representation of the entire sequence for downstream tasks.
- For example, in a classification task:
  - The `pooled_output` is passed to a dense layer to predict the class labels.
  
If you need token-level predictions (e.g., in Named Entity Recognition or Question Answering), you would instead use the **token embeddings** (`sequence_output`).

## cosine similarity example
### it simply means two words are similar or not

### https://becominghuman.ai/sequential-vs-functional-model-in-keras-20684f766057

## Functional Model

### Bert Layers

In [27]:
# Define the input layer (symbolic tensor)
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name="text")

# Preprocess text using the BERT preprocessing layer
preprocessed_text = bert_preprocess(text_input)  # No change here

# Pass preprocessed text through the BERT encoder
outputs  = bert_encoder(preprocessed_text)

# Extract pooled_output (CLS token representation)
# pooled_output = bert_outputs["pooled_output"]

# # Define the functional model
# model = tf.keras.Model(inputs=text_input, outputs=pooled_output)

# # Run the model with actual data
# sample_text = ["This is a test sentence."]  # Actual input data
# result = model(sample_text)  # This is valid because it's after defining the model
# print(result)


### Neural Network layer

In [28]:
# Neural network layers

l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

### Final model

In [29]:
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [30]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text (InputLayer)           [(None,)]                    0         []                            
                                                                                                  
 keras_layer (KerasLayer)    {'input_type_ids': (None,    0         ['text[0][0]']                
                             128),                                                                
                              'input_mask': (None, 128)                                           
                             , 'input_word_ids': (None,                                           
                              128)}                                                               
                                                                                              

### Model Compile

In [31]:
METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=METRICS)

### Train model

In [32]:
model.fit(X_train, y_train, epochs= 10)

Epoch 1/10
35/35 [==============================] - 24s 361ms/step - loss: 0.6934 - accuracy: 0.5491 - precision: 0.5497 - recall: 0.5429
Epoch 2/10
35/35 [==============================] - 12s 347ms/step - loss: 0.5253 - accuracy: 0.8125 - precision: 0.8028 - recall: 0.8286
Epoch 3/10
35/35 [==============================] - 12s 350ms/step - loss: 0.4346 - accuracy: 0.8652 - precision: 0.8685 - recall: 0.8607
Epoch 4/10
35/35 [==============================] - 12s 350ms/step - loss: 0.3856 - accuracy: 0.8750 - precision: 0.8608 - recall: 0.8946
Epoch 5/10
35/35 [==============================] - 13s 358ms/step - loss: 0.3576 - accuracy: 0.8964 - precision: 0.8868 - recall: 0.9089
Epoch 6/10
35/35 [==============================] - 13s 378ms/step - loss: 0.3288 - accuracy: 0.8946 - precision: 0.8771 - recall: 0.9179
Epoch 7/10
35/35 [==============================] - 12s 357ms/step - loss: 0.3086 - accuracy: 0.9107 - precision: 0.8993 - recall: 0.9250
Epoch 8/10
35/35 [================

## Evaluate Model

In [33]:
model.evaluate(X_test, y_test)

12/12 [==============================] - 5s 351ms/step - loss: 0.2863 - accuracy: 0.9064 - precision: 0.8725 - recall: 0.9519


[0.2863372564315796,
 0.9064171314239502,
 0.8725489974021912,
 0.9518716335296631]

In [34]:
y_predicted = model.predict(X_test)
y_predicted = y_predicted.flatten()

12/12 [==============================] - 5s 337ms/step


In [35]:
import numpy as np

y_predicted = np.where(y_predicted > 0.5, 1, 0)
y_predicted

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text (InputLayer)           [(None,)]                    0         []                            
                                                                                                  
 keras_layer (KerasLayer)    {'input_type_ids': (None,    0         ['text[0][0]']                
                             128),                                                                
                              'input_mask': (None, 128)                                           
                             , 'input_word_ids': (None,                                           
                              128)}                                                               
                                                                                            

In [36]:
reviews = [
    'Enter a chance to win $5000, hurry up, offer valid until march 31, 2021',
    'You are awarded a SiPix Digital Camera! call 09061221061 from landline. Delivery within 28days. T Cs Box177. M221BP. 2yr warranty. 150ppm. 16 . p p£3.99',
    'it to 80488. Your 500 free text messages are valid until 31 December 2005.',
    'Hey Sam, Are you coming for a cricket game tomorrow',
    "Why don't you wait 'til at least wednesday to see if you get your ."
]
model.predict(reviews)

1/1 [==============================] - 1s 1s/step


array([[0.79403514],
       [0.8718212 ],
       [0.8438156 ],
       [0.26610857],
       [0.1505799 ]], dtype=float32)